title: "Calogero Bonasia"
description: "Project Manager | Architetture digitali | Governance del sapere"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

url: "https://kalosbonasia.github.io"
baseurl: ""  # lascialo vuoto se usi kalosbonasia.github.io direttamente

author:
  name: "Calogero Bonasia"
  email: "calogero@example.org"

markdown: kramdown
theme: null
