remote_theme: pages-themes/modernist

# Informazioni di base
locale: "it-IT"
title: "Calogero Bonasia"
description: "Project Manager | Architetture digitali | Governance del sapere"
url: "https://kalosbonasia.github.io"
baseurl: ""
repository: "kalosbonasia/kalos-cv"

# Autore
author:
  name: "Calogero Bonasia"
  email: "calogero@example.org"
  bio: "Project Manager con esperienza in PA, difesa e settori regolamentati. Esperto in architetture digitali adattive e governance del sapere."
  location: "Italia"
  avatar: "/images/profile.png"
  github: kalosbonasia
  linkedin: calogerobonasia

# SEO
social:
  type: Person
  name: "Calogero Bonasia"
  links:
    - https://github.com/kalosbonasia
    - https://www.linkedin.com/in/calogerobonasia
og_image: "/images/profile.png"
og_description: "Sito personale di Calogero Bonasia – Project Manager"

# Impostazioni di lettura
include:
  - _pages
  - files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Conversione Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  toc_levels: 1..6
  auto_ids: true

# Plugin supportati da GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
